name: Continuous Deployment â™¾ï¸ğŸš€

on:
  release:
    types:
      - published

jobs:
  Pack-and-Publish:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Check out code ğŸ‘€
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore packages and dependencies ğŸ“¥ğŸ“¦
        run: dotnet restore

      - name: Build For Release ğŸ‘·â€â™€ğŸ—ï¸
        run: dotnet build -c Release --no-restore

      - name: Run tests ğŸ©ºğŸ”¬ğŸ§‘â€ğŸ”¬
        run: dotnet test -c Release --no-restore

      - name: Pack the package
        run: dotnet pack .\scr\Roseau.GuardHelpers\Roseau.GuardHelpers.csproj -c Release --no-restore --output .\scr\Roseau.GuardHelpers\nupkgs

      - name: Publish the package
        run: dotnet nuget push .\scr\Roseau.GuardHelpers\nupkgs\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
