name: Continuous Deployment â™¾ï¸ğŸš€

on:
  release:
    types:
      - published

jobs:
  on-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name = 'release' }}
    steps:
      - run: echo "The triggering workflow passed"