name: Continuous Deployment â™¾ï¸ğŸš€

on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - "Continuous Integration â™¾ï¸â¬‡ï¸"
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  on-Continuous-Integration-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The triggering workflow passed"
  
  on-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The triggering workflow passed"